baseURL = "http://47.97.19.70/"
title = "Data Engineering Hub"
theme = "hugo-geekdoc"

[params]
    geekdocLogo = "logo.png"

    # (Optional, default false) Collapse all menu entries, can not be overwritten
    # per page if enabled. Can be enabled per page via 'geekdocCollapseSection'.
    geekdocCollapseAllSections = true


    # (Optional, default true) Display a "Back to top" link in the site footer.
    geekdocBackToTop = true



    # (Optional, default 'title') Configure how to sort file-tree menu entries. Possible options are 'title', 'linktitle',
    # 'date', 'publishdate', 'expirydate' or 'lastmod'. Every option can be used with a reverse modifier as well
    # e.g. 'title_reverse'.
    geekdocFileTreeSortBy = "date"